try:
    from divergulent._version import version as __version__
except ImportError:
    # _version.py is generated by setuptools_scm at build time; fall back
    # when running from a source tree that has not been built.
    __version__ = '0.0.0+unknown'
