"""Tests for tools/generated-marking/measure.py -- the phase-1 measurement tool.

All offline: a tiny fixture corpus (sqlite ``patch`` index + content-addressed bodies) is
built in a tempdir per test, matching the real corpus layout described in
docs/plans/PLAN-generated-marking-phase-01-scanner.md (phase 1, step S2). ``measure.py``
is loaded via ``importlib`` (no subprocess) since it lives under ``tools/``, not the
importable ``divergulent`` package.

Fixture fingerprints (one representative body each):

* ``fp-gatos`` -- a gatos-shaped patch: ``configure`` (autoconf 2.59 banner),
  ``Makefile.in`` (name only, no banner in the touched region), and a hand-written
  ``src/foo.c`` residue line.
* ``fp-handonly`` -- purely hand-written, no signals at all.
* ``fp-banneronly`` -- ``acinclude.m4`` (outside the name set) carrying an automake
  banner: the gap-list case, and the ``acinclude.m4`` check's positive case.
* ``fp-donotedit`` -- a ``DO NOT EDIT`` line on a file outside the name set: the
  candidate-only family, which must never mark anything in ``scan()``.
* ``fp-missing`` -- a row whose body file does not exist on disk.
* ``fp-dedup`` -- two ``patch`` rows sharing one fingerprint with different
  ``raw_sha256``\\ s; only the body for ``MIN(raw_sha256)`` is ever read, proven by
  planting a distinct, easily-detected signal (an ``ltmain.sh`` name match) in the body
  that must NOT be picked.
"""
import importlib.util
import json
import os
import sqlite3
import tempfile

import testtools

from divergulent.tests.test_generated import _file_diff

_MEASURE_PATH = os.path.join(
    os.path.dirname(__file__), '..', '..', 'tools', 'generated-marking', 'measure.py')


def _load_measure():
    """Import ``measure.py`` fresh via ``importlib`` (it is not part of the package)."""
    spec = importlib.util.spec_from_file_location('generated_marking_measure', _MEASURE_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


measure = _load_measure()

GATOS_TEXT = ''.join([
    _file_diff('configure', [' # Generated by GNU Autoconf 2.59.', '-old', '+new']),
    _file_diff('Makefile.in', ['-CFLAGS = -O1', '+CFLAGS = -O2']),
    _file_diff('src/foo.c', ['+int fixed = 1;']),
])
# changed: configure=2 (marked, name+banner), Makefile.in=2 (marked, name only),
# src/foo.c=1 (unmarked); total=5, generated=4, coverage=0.8 -> [0.5, 0.9) bucket.

HAND_ONLY_TEXT = _file_diff('src/bar.c', [' context', '-x', '+y'])
# changed=2, nothing marked, coverage=0.0 -> zero bucket.

BANNER_ONLY_TEXT = _file_diff('acinclude.m4', [
    ' # Makefile.in generated by automake 1.9.6 from Makefile.am.', '-old', '+new'])
# acinclude.m4 is deliberately outside the name set: marked banner-only, signals ==
# ('banner',). changed=2, generated=2, coverage=1.0 -> [0.9, 1.0] bucket.

DO_NOT_EDIT_TEXT = _file_diff('src/table.h', [
    ' /* DO NOT EDIT: this file is machine-made. */',
    '+static const int table[] = { 1, 2, 3 };'])
# The candidate-only family: a hit for candidate_banner_hits, but scan() marks nothing.
# changed=1, coverage=0.0 -> zero bucket.

DEDUP_TEXT = _file_diff('src/qux.c', [' ctx', '-a', '+b'])
# The representative body for the dedup fingerprint: purely hand-written.

DEDUP_DECOY_TEXT = _file_diff('ltmain.sh', [' # ltmain.sh (GNU libtool) 9.9.9', '+decoy'])
# The NON-representative body for the same fingerprint (higher raw_sha256, never read).
# If dedup ever broke and this got scanned too, 'ltmain.sh' would show a match count of
# 1 instead of 0 -- an easily-detected tripwire for the bug.


def _write_body(corpus_dir, sha, text):
    directory = os.path.join(corpus_dir, 'bodies', sha[:2])
    os.makedirs(directory, exist_ok=True)
    with open(os.path.join(directory, sha), 'w', encoding='utf-8') as handle:
        handle.write(text)


def _build_fixture_corpus(corpus_dir):
    """Lay down the sqlite ``patch`` index and bodies/ for the fixture fingerprints."""
    os.makedirs(corpus_dir, exist_ok=True)

    sha_gatos = '1111111111111111111111111111111111111111111111111111111111111111'
    sha_hand = '2222222222222222222222222222222222222222222222222222222222222222'
    sha_banner = '3333333333333333333333333333333333333333333333333333333333333333'
    sha_donotedit = '4444444444444444444444444444444444444444444444444444444444444444'
    sha_missing = '5555555555555555555555555555555555555555555555555555555555555555'
    sha_dedup_min = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
    sha_dedup_other = 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'

    _write_body(corpus_dir, sha_gatos, GATOS_TEXT)
    _write_body(corpus_dir, sha_hand, HAND_ONLY_TEXT)
    _write_body(corpus_dir, sha_banner, BANNER_ONLY_TEXT)
    _write_body(corpus_dir, sha_donotedit, DO_NOT_EDIT_TEXT)
    _write_body(corpus_dir, sha_dedup_min, DEDUP_TEXT)
    _write_body(corpus_dir, sha_dedup_other, DEDUP_DECOY_TEXT)
    # sha_missing is deliberately never written.

    rows = [
        ('pkg-gatos', '1.0', '01-gatos.patch', sha_gatos, 'fp-gatos'),
        ('pkg-hand', '1.0', '01-hand.patch', sha_hand, 'fp-handonly'),
        ('pkg-banner', '1.0', '01-banner.patch', sha_banner, 'fp-banneronly'),
        ('pkg-dne', '1.0', '01-donotedit.patch', sha_donotedit, 'fp-donotedit'),
        ('pkg-missing', '1.0', '01-missing.patch', sha_missing, 'fp-missing'),
        ('pkg-dedup', '1.0', '01-dedup-a.patch', sha_dedup_min, 'fp-dedup'),
        ('pkg-dedup', '1.0', '01-dedup-b.patch', sha_dedup_other, 'fp-dedup'),
    ]

    connection = sqlite3.connect(os.path.join(corpus_dir, 'fingerprints.sqlite'))
    try:
        connection.execute(
            'CREATE TABLE patch ('
            'source_package TEXT NOT NULL, '
            'version TEXT NOT NULL, '
            'patch_name TEXT NOT NULL, '
            'raw_sha256 TEXT NOT NULL, '
            'normalisation_version INTEGER NOT NULL, '
            'fingerprint TEXT NOT NULL)')
        connection.executemany(
            'INSERT INTO patch (source_package, version, patch_name, raw_sha256, '
            'normalisation_version, fingerprint) VALUES (?, ?, ?, ?, 1, ?)',
            rows)
        connection.commit()
    finally:
        connection.close()


class MeasureCorpusTestCase(testtools.TestCase):

    def setUp(self):
        super().setUp()
        tempdir = tempfile.TemporaryDirectory()
        self.addCleanup(tempdir.cleanup)
        self.corpus_dir = os.path.join(tempdir.name, 'corpus')
        _build_fixture_corpus(self.corpus_dir)
        self.report = measure.build_report(self.corpus_dir)

    # -- totals: dedup and missing-body accounting -------------------------

    def test_totals_count_missing_and_dedup_correctly(self):
        totals = self.report['totals']
        # 6 distinct fingerprints; 1 missing body; the dedup fingerprint scanned once.
        self.assertEqual(5, totals['fingerprints_scanned'])
        self.assertEqual(1, totals['bodies_missing'])

    def test_dedup_never_reads_the_non_representative_body(self):
        # If MIN(raw_sha256) selection broke, the decoy body's 'ltmain.sh' would show up.
        self.assertEqual(0, self.report['name_match_counts']['ltmain.sh']['total'])

    # -- (a) per-name match counts ------------------------------------------

    def test_name_match_counts_for_configure_and_makefile_in(self):
        counts = self.report['name_match_counts']
        self.assertEqual({'total': 1, 'banner_count': 1, 'banner_fraction': 1.0}, counts['configure'])
        self.assertEqual({'total': 1, 'banner_count': 0, 'banner_fraction': 0.0}, counts['Makefile.in'])

    def test_unmatched_names_report_zero(self):
        counts = self.report['name_match_counts']
        self.assertEqual({'total': 0, 'banner_count': 0, 'banner_fraction': 0.0}, counts['missing'])

    # -- (b) the gap list -----------------------------------------------------

    def test_gap_list_has_the_acinclude_banner_only_entry(self):
        gap_list = self.report['gap_list']
        self.assertEqual(1, len(gap_list))
        entry = gap_list[0]
        self.assertEqual('acinclude.m4', entry['basename'])
        self.assertEqual(1, entry['count'])
        self.assertEqual(['acinclude.m4'], entry['examples'])
        self.assertEqual(['automake 1.9.6'], entry['generators'])

    # -- (c) coverage distribution --------------------------------------------

    def test_coverage_buckets(self):
        buckets = self.report['coverage_distribution']['buckets']
        self.assertEqual(3, buckets['zero'])           # handonly, donotedit, dedup
        self.assertEqual(0, buckets['lt_0_5'])
        self.assertEqual(1, buckets['ge_0_5_lt_0_9'])  # gatos: 0.8
        self.assertEqual(1, buckets['ge_0_9'])         # acinclude banner-only: 1.0

    def test_ge_0_5_list_sorted_by_coverage_descending(self):
        records = self.report['coverage_distribution']['ge_0_5_list']
        self.assertEqual(['fp-banneronly', 'fp-gatos'], [r['fingerprint'] for r in records])
        self.assertAlmostEqual(1.0, records[0]['coverage'])
        self.assertAlmostEqual(0.8, records[1]['coverage'])
        self.assertEqual(1, records[1]['residue_changed'])
        self.assertEqual(4, records[1]['generated_changed'])
        self.assertEqual(5, records[1]['total_changed'])

    # -- (d) low-frequency-name adjudication -----------------------------------

    def test_low_frequency_names_lists_the_matched_paths(self):
        low_freq = self.report['low_frequency_names']
        self.assertEqual(
            [{'path': 'configure', 'fingerprint': 'fp-gatos'}], low_freq['configure'])
        self.assertEqual(
            [{'path': 'Makefile.in', 'fingerprint': 'fp-gatos'}], low_freq['Makefile.in'])
        # Zero-match names are still present, with an empty path list.
        self.assertEqual([], low_freq['ltmain.sh'])

    # -- (e) acinclude.m4 check -------------------------------------------------

    def test_acinclude_check(self):
        acinclude = self.report['acinclude']
        self.assertEqual(1, acinclude['touched'])
        self.assertEqual(1, acinclude['banner_marked'])
        self.assertEqual(['automake 1.9.6'], acinclude['generators'])

    # -- (f) multi-banner report -------------------------------------------------

    def test_no_multi_banner_files_in_the_fixture(self):
        self.assertEqual({'count': 0, 'examples': []}, self.report['multi_banner'])

    # -- (g) candidate do-not-edit family -----------------------------------------

    def test_candidate_family_reports_the_do_not_edit_hit(self):
        candidate = self.report['candidate_family']
        self.assertEqual(1, candidate['total_files_hit'])
        self.assertEqual([{'basename': 'table.h', 'count': 1}], candidate['basename_counts'])
        self.assertEqual(1, len(candidate['samples']))
        sample = candidate['samples'][0]
        self.assertEqual('fp-donotedit', sample['fingerprint'])
        self.assertEqual('src/table.h', sample['path'])
        self.assertIn('DO NOT EDIT', sample['snippet'])

    # -- top-level shape -----------------------------------------------------

    def test_report_has_every_expected_top_level_key(self):
        self.assertEqual({
            'name_match_counts', 'gap_list', 'coverage_distribution', 'low_frequency_names',
            'acinclude', 'multi_banner', 'candidate_family', 'totals',
        }, set(self.report))


class MeasureCliTestCase(testtools.TestCase):

    def setUp(self):
        super().setUp()
        tempdir = tempfile.TemporaryDirectory()
        self.addCleanup(tempdir.cleanup)
        self.corpus_dir = os.path.join(tempdir.name, 'corpus')
        _build_fixture_corpus(self.corpus_dir)
        self.output_path = os.path.join(tempdir.name, 'results.json')

    def test_main_writes_a_loadable_json_report(self):
        exit_code = measure.main([self.corpus_dir, '--output', self.output_path])
        self.assertEqual(0, exit_code)
        self.assertTrue(os.path.exists(self.output_path))

        with open(self.output_path, encoding='utf-8') as handle:
            loaded = json.load(handle)

        self.assertEqual({
            'name_match_counts', 'gap_list', 'coverage_distribution', 'low_frequency_names',
            'acinclude', 'multi_banner', 'candidate_family', 'totals',
        }, set(loaded))
        self.assertEqual(5, loaded['totals']['fingerprints_scanned'])
        self.assertEqual(1, loaded['totals']['bodies_missing'])

    def test_limit_restricts_the_scanned_fingerprints(self):
        exit_code = measure.main([self.corpus_dir, '--output', self.output_path, '--limit', '1'])
        self.assertEqual(0, exit_code)
        with open(self.output_path, encoding='utf-8') as handle:
            loaded = json.load(handle)
        # Only the first fingerprint in sorted order is scanned or counted missing.
        self.assertEqual(1, loaded['totals']['fingerprints_scanned'] + loaded['totals']['bodies_missing'])
