name: Sanity checks

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: [self-hosted, static]

    steps:
      - name: Checkout code with two commits
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Install tox in a venv
        run: |
          rm -rf test-venv
          python3 -m venv test-venv
          test-venv/bin/pip install --upgrade pip
          test-venv/bin/pip install tox
          echo "${GITHUB_WORKSPACE}/test-venv/bin" >> "${GITHUB_PATH}"

      - name: Lint with flake8
        run: |
          tox -eflake8

      - name: Run unit tests
        run: |
          tox -epy3
